### ISSUE TITLE
feat: Add aggregation capabilities for pandas `DataFrameBaseView`

### ISSUE THREAD

**Issue by PatrykWyzgowski** [deepsense-ai/db-ally#81]
### Feature description

Implement aggregation mechanism for `DataFrameBaseView`. It is marked with TODO in [pandas_base.py](https://github.com/deepsense-ai/db-ally/blob/main/src/dbally/views/pandas_base.py) file in [this PR](https://github.com/deepsense-ai/db-ally/pull/62):

```python
async def apply_aggregation(self, aggregation: IQLQuery) -> None:
    """
    Applies the aggregation of choice to the view.

    Args:
        aggregation: IQLQuery object representing the aggregation to apply
    """
    # TODO - to be covered in a separate ticket.`
```

### Motivation

Currently single aggregation is supported by `SqlAlchemyBaseView`, though its parent `MethodsBaseView` (also a parent for `DataFrameBaseView`) posseses and interface for this. To unify capabilities of the most high-level views implemented (for SQLAlchemy and Pandas respectively) one should implement aggregation mechanism for `DataFrameBaseView` as well.

**Comment by micpst** [comment]
This will be implemented in #62
